#!/bin/bash
#======================================================================================
# Install the Java Point of Sale class project on Ubuntu Linux.
#
# Arguments:
# (None)		
#
# Version: 1.1.0
# Date: 02-May-2014
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/java-point-of-sale-project"
export PROJECT_DIR="$HOME/workspace/point-of-sale"

echo
echo '============================================================='
echo "Cloning project files into $HOME/workspace/point-of-sale..."

mkdir -p "$HOME/workspace"
cd "$HOME/workspace"
git clone https://github.com/neopragma-training

echo
echo '============================================================='
echo "Copying scripts to $HOME/bin..."

mkdir -p "$HOME/bin"
mkdir -p "$HOME/tmp"
cp authserver "$HOME/bin"
chmod +x "$HOME/bin/authserver"
cp store "$HOME/bin"
chmod +x "$HOME/bin/store"
cp register "$HOME/bin"
chmod +x "$HOME/bin/register"

echo
echo '============================================================='
echo "Appending $HOME/bin to PATH in $HOME/.bashrc..."

echo "export PATH=$PATH:$HOME/bin" >> "$HOME/.bashrc"
pushd "$HOME"
. .bashrc
popd

echo
echo '============================================================='
echo "Copying project documentation to the desktop..."

cp -R Point-of-Sale-Docs "$HOME/Desktop"

echo
echo '============================================================='
echo "Installing MongoDB..."

sudo apt-get -y -f install mongodb-server

echo
echo '============================================================='
echo "Installing dependencies for $HOME/workspace/point-of-sale/credit-authorization..."

pushd "$HOME/workspace/point-of-sale/credit-authorization"
bundle install
popd

echo
echo '============================================================='
echo "Installing dependencies for $HOME/workspace/point-of-sale/point-of-sale..."

pushd "$HOME/workspace/point-of-sale"
mvn eclipse:eclipse
mvn clean install
popd




