#!/bin/bash
#============================================================
# Start and stop the point of sale Store application
#
# 10 May 2014 v 1.0
#============================================================
APPDIR="$HOME/workspace/point-of-sale/target"

TEMP=`getopt -o hv --long help,version \
             -n 'store' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"

function version {
  echo 'store start/stop script version 1.0 10 May 2014'
}

function help {
  echo 'Stop and start the POS Store application'
  echo '  store -h      Usage help'
  echo '  store --help  Usage help'
  echo '  store start   Start the server'
  echo '  store stop    Stop the server'
  echo '  store restart Stop and start the server'
}

function startserver {
  java -jar "$APPDIR/pos-store.jar" &
  echo $! > ~/tmp/store.pid
}

function stopserver {
  kill `cat ~/tmp/store.pid`
}

while true; do
  case "$1" in
    -h | --help ) help ; exit 0 ;;
    -v | --version ) version ; exit 0 ;;
    * ) shift ; break ;;
  esac
done

if [[ "$1" == "start" ]] ; then startserver ; fi
if [ "$1" == "stop" ] ; then stopserver ; fi
if [ "$1" == "restart" ] ; then stopserver ; startserver ; fi

exit 0
